### PR TITLE
fix struct  nested reflection

### PR DESCRIPTION
**Pull request by aixj1984**
- With pull requests:
    - Open your pull request against `main`
    - Your pull request should have no more than two commits, if not you should squash them.
    - You should pass all tests by `go test -v ./...` at the project root path in local. 
    - It should pass all tests in the available continuous integration systems such as GitHub Actions.
    - You should add/modify tests to cover your proposed code changes.
    - If your pull request contains a new feature, please document it on the README.

#38 这个问题只解决了一层嵌套 
现在修改代码，通过递归方式，解决多层嵌套的问题

### CODE REVIEW

**Comment by afumu** [comment]
> * With pull requests:
>   
>   * Open your pull request against `main`
>   * Your pull request should have no more than two commits, if not you should squash them.
>   * You should pass all tests by `go test -v ./...` at the project root path in local.
>   * It should pass all tests in the available continuous integration systems such as GitHub Actions.
>   * You should add/modify tests to cover your proposed code changes.
>   * If your pull request contains a new feature, please document it on the README.
> 
> #38 这个问题只解决了一层嵌套 现在修改代码，通过递归方式，解决多层嵌套的问题

good！

**Comment by afumu** [comment]
@aixj1984  请在评论下面回复这句话哈

image

**Comment by aixj1984** [comment]
I have read the ClDocument and ! hereby sign the CLA

**Comment by aixj1984** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
